# apiVersion: apps/v1
# #
# kind: Deployment
# metadata:
#   name: minio-deployment
#   namespace: minio-ns
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: minio
#   template:
#     metadata:
#       labels:
#         app: minio
#     spec:
#       containers:
#       - name: minio
#         image: tgwalker93/minio-demucs:v1
#         env:
#           - name: MINIO_HOST
#             value: "minio:9000"
# ---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio-ns
spec:
  type: ExternalName
  externalName: minio-proj.minio-ns.svc.cluster.local