apiVersion: apps/v1

kind: Deployment
metadata:
  name: worker-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: tgwalker93/worker-server
        resources:
          requests:
            cpu: 250m
            memory: 100Mi
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"        
        - name: MINIO_HOST
          value: "minio:9000"        
        # resources:
        #   limits:
        #     cpu: "3"
        #   requests:
        #     cpu: "1"
      # resources:
      #   limits:
      #     nvidia.com/gpu: 1
      # nodeSelector:
      #   cloud.google.com/gke-accelerator: nvidia-t4
        # env:
        #   - name: MINIO_HOST
        #     value: "minio:9000"      
        #   - name: REDIS_HOST
        #     value: "6379"
        #needs redis host and redis port
        #needs image for worker